<div class="ubicacion m-t-10p">
    <div class="ayuda">Referencias > Eliminar referencia / Libro</p>
    </div>
</div>
<main>
    <nav class="nav-libro m-t-10p">
        <ul class="navmenu">
            <li class="active"><a href="index.php?accion=eliminar">eliminar libro</a></li>
            <li><a href="index.php?accion=eliminarJournal">Eliminar Journal-Conferencia</a></li>
        </ul>
    </nav>


    <div class="busqueda m-t-20p eliminar">

        <div class="extraerCategoria">

            <div class="buscadorLibro active original">
                <input type="text" placeholder="Buscar Categoria de Libro a eliminar">
                <div class="logo-buscar"><i class="material-icons">search</i></div>
            </div>

        </div>


    </div>
    <section class="modal hidden verde">
        <div class="view-modal exitoeliminar">
            <div class="title">
                <h3>Se elimino correctamente</h3>
            </div>
        </div>
    </section>
    <div class="container-ckekeds m-t-20p">
        <div class="mostrar_buscados">

        </div>
    </div>
</main>
<section class="modal hidden red">
    <div class="view-modal">
        <div class="title">
            <h3>Ingrese Nuevo Autor y sus Apellidos</h3>
        </div>
    </div>
</section>
<section class="modal red hidden hello">
    <div class="view-modal modal-obliogatorios">
        <div class="title">
            <h3>Todos los datos son obligatorios</h3>
        </div>
    </div>
</section>